name:  Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug
      working-directory: first

    - name: Build
      run: cmake --build build
      working-directory: first

    - name: Run src1
      run: ./build/src1
      working-directory: first

    - name: Run src2
      run: ./build/src2
      working-directory: first

    - name: Run lab12
      run: ./build/lab12
      working-directory: 2sem/2sem/labs

    - name: Run lab11
      run: ./build/lab11
      working-directory: 2sem/2sem/labs

    - name: Run lab2
      run: ./build/lab2
      working-directory: 2sem/2sem/labs
